### ISSUE TITLE
[SUGGESTION] Split Screen Pathway Overlap

### ISSUE THREAD

**Issue by CHE-11** [pjeby/quick-explorer#10]
A lot of the time I work from my laptop where I have a small workspace and have both a browser and obsidian open. With this layout, the pathway in the top bar overlaps the title set by obsidian. Would it be possible to remove the obsidian native title when obsidian window is < a certain window size? Or another way to avoid this overlap?

BTW I love this add-on. Thank you so much for making it!!

**Comment by pjeby** [comment]
You can use CSS to set an opaque background for `#quick-explorer`, which will make it block out the title, e.g.

```css
div#quick-explorer {
    background-color: var(--background-modifier-cover) !important;
}
```

This used to be the default, but it made the explorer bar unusable on certain light themes that used titlebar text colors close to the background-modifier-cover color.
