### ISSUE TITLE
Quick Explorer collides with Title Bar

### ISSUE THREAD

**Issue by MalignantCarp** [pjeby/quick-explorer#20]
When you have a rather deep tree, the Obsidian title bar gets mangled:

![image](https://user-images.githubusercontent.com/93364935/140600223-66de91e8-7826-44cb-87fa-7ed65cf1e12e.png)

It might need to move down a line worth of space to avoid colliding with the title bar.

**Comment by pjeby** [comment]
This can be worked around with CSS, e.g.:

```css
div#quick-explorer {
    background-color: var(--background-modifier-cover) !important;
}
```

It's not the default because some themes don't play well with an explicit setting of the title bar background color.
