### ISSUE TITLE
[feature request] show Obsidian Title on the left

### ISSUE THREAD

**Issue by Lantaio** [pjeby/quick-explorer#55]
Hi, @pjeby. Can you add an option to show the Obsidian Title on the left in Style Settings? Next are the backward and forward buttons. Then the QE breadcrumb. Thanks in advance!

**Comment by pjeby** [comment]
In Obsidian 0.16, the breadcrumbs and history arrows are on the *tab* title bar by default, and in most of Obsidian's new frame modes there is no ability to modify the window title bar -- or no title bar at all.

For these reasons, I will likely be phasing out the QE breadcrumbs, and so don't plan to add any new features for managing the window titlebar.

You can use a CSS snippet to do this yourself, however.  Something like this should probably work:

```css
 .titlebar-text.qe-replacement {
    text-align: left;
    justify-content: flex-start;
    align-items: flex-start;
}
```
