### ISSUE TITLE
[REQUEST] Options for visuals

### ISSUE THREAD

**Issue by firinael** [pjeby/quick-explorer#6]
Hi, I'd like to always have the `/` displayed even when I'm in a note in the root of the vault, and I'd like for the file extension to be shown (especially important for those that have plugins that allow for editing of .csv files, .txt, etc).

Could these be added as toggles in the plugin's options?

Thank you!

**Comment by pjeby** [comment]
The / is never displayed, because you can't do anything to the vault root, nor to its containing folder.  (Which is what putting a / breadcrumb would mean: i.e. show items in the folder that contains the vault, not the contents of the vault root.)

If your active file is in the vault root, then clicking on the filename displays the content of the vault root.  (As will the commands for browsing the current folder and browsing the vault root.)

As for the extensions, they are shown, but it's possible your theme colors are such that you can't read them.  They appear in a smaller text, all caps, slightly faded, aligned to the right of the file.  The other possibility is that you have the Obsidian option to show unsupported files turned off - look under Files and Links in the Obsidian settings for "Detect all file extensions".  If it's off, Quick Explorer will only show Obsidian-supported file types, so if you don't have the CSV plugin active it won't show any CSV files.

If it's on and you're sure that you have a file with an extension that's not showing the extension, even when you move to select that file, then the theme is likely the issue: try switching to the default them (i.e. "None") and see if they're visible then.

**Comment by firinael** [comment]
What I wanted for the file extensions was displaying them as `note.md` and `picture.png` instead of `note` and `picture [PNG]`.

And I wanted the breadcrumb (didn't know that was the name for it) for aesthetic reasons. It's just weird seeing a file explorer without showing the root `/`.

**Comment by pjeby** [comment]
You can do both of those things with a CSS snippet:

```css
/* Precede first breadcrumb with / (unless it's / already) */
#quick-explorer .explorable:first-child:not(data-file-path="/")::before { content: "/ "; }

/* Add .md to notes */
.qe-popup-menu .menu-item[data-file-path$=".md"] .menu-item-title::after { content: ".md"; }

/* Show file extensions as part of filename */
.qe-popup-menu .menu-item:not(.is-folder) .nav-file-tag {
    margin-left: -3px !important;  /* Nudge the extension closer to the name */
    text-transform: none; /* turn off uppercase */

    /* Style text to be mostly the same as the filename */
    font-size: 14px;
    color: var(--text-normal);
    opacity: 1 !important;
    font-weight: normal;
    display: inline;
}

/* Add a '.' before the extension */
.qe-popup-menu .menu-item:not(.is-folder) .nav-file-tag::before { content: "."; }
.qe-popup-menu .menu-item:not(.is-folder) .menu-item-title { flex-grow: unset !important; }
```

This basically does what you're asking for, if you add it to a CSS snippet in your vault's snippets folder, and enable it.  Some adjustments may be needed if your theme is sufficiently different from the default.

**Comment by firinael** [comment]
I had to remove the `:not` from  `#quick-explorer .explorable:first-child:not(data-file-path="/")::before { content: "/ "; }` but it works.

Anything I can do about these two dots? I've tried using `:first-child` but that didn't work out.

![image](https://user-images.githubusercontent.com/67032657/132779566-efcfdece-6e8d-43a0-b38d-f7aeba82eb5b.png)

**Comment by pjeby** [comment]
Hm.  That line was supposed to be:

```css
#quick-explorer .explorable:first-child:not([data-file-path="/"])::before { content: "/ "; }
```

Apparently I lost the square brackets somewhere along the way.

I'm not clear on why there are slashes on the filenames in your screenshot, though, nor what it is you're trying to do with the `..` (which is the symbol for "go up a directory" in all operating systems).

As for adding the / to  the end, at this point I'm going to bow out on providing detailed CSS advice.  You should probably ask someone on Discord or the forums to help you with any further stylings.
