### ISSUE TITLE
Q re CSS for Hiding Folders

### ISSUE THREAD

**Issue by julroger2013** [pjeby/quick-explorer#65]
Not really an issue, per se, but a question. 

I think, based on some of your prior responses to issues here or to questions on Discord, that it should be possible to hide specified file paths from the QE UI. Is that right? 

Pretty sure CSS would be the way to do this, but I'm not sure what sort of snippet I would need.

**Comment by pjeby** [comment]
Something like this should do the trick:

```css
.menu-item[data-file-path="Path/To/Folder"] { display: none !important;}
```
